boardgame_platform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("boardgames.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

boardgames/urls.py
from django.urls import path
from boardgames.views import (
    index,
    BoardGameListView,
    EventListView,
    PlayerListView,
    BoardGameDetailView,
    EventDetailView,
    EventCreateView,
    toggle_assign_to_event,
    EventUpdateView,
    EventDeleteView,
    BoardGameCreateView,
    BoardGameUpdateView,
    BoardGameDeleteView,
    RegisteredEventsByUserListView,
)

app_name = "boardgames"
urlpatterns = [
    path("", index, name="index"),
    path("boardgames/", BoardGameListView.as_view(), name="board-game-list"),
    path("events/", EventListView.as_view(), name="event-list"),
    path("players/", PlayerListView.as_view(), name="player-list"),
    path(
        "boardgames/<int:pk>/", BoardGameDetailView.as_view(), name="board-game-detail"
    ),
    path("boardgames/create/", BoardGameCreateView.as_view(), name="board-game-create"),
    path(
        "boardgames/update/<int:pk>/",
        BoardGameUpdateView.as_view(),
        name="board-game-update",
    ),
    path(
        "boardgames/delete/<int:pk>/",
        BoardGameDeleteView.as_view(),
        name="board-game-delete",
    ),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event-detail"),
    path("events/create/", EventCreateView.as_view(), name="event-create"),
    path("events/update/<int:pk>", EventUpdateView.as_view(), name="event-update"),
    path("events/delete/<int:pk>/", EventDeleteView.as_view(), name="event-delete"),
    path("events/<int:pk>/toggle/", toggle_assign_to_event, name="event-toggle"),
    path("my_events/", RegisteredEventsByUserListView.as_view(), name="my-events"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("boardgames.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

templates/includes/pagination.html
{% load query_transform %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}">prev</a>
      </li>
    {% endif %}

    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul>
              <li class="active"><a href="{% url "boardgames:index" %}">Home</a></li>
              <li><a href="{% url "boardgames:board-game-list" %}">Boardgames</a></li>
              <li><a href="{% url "boardgames:event-list" %}">Events</a></li>
              {% if user.is_authenticated %}
               <li>User: {{ user.get_username }}</li>

               <li><a href="{% url 'boardgames:my-events' %}">My Events</a></li>

               <li>
                 <form id="logout-form" method="post" action="{% url 'logout' %}">
                   {% csrf_token %}
                   <button type="submit" class="btn btn-link">Logout</button>
                 </form>
               </li>
               {% else %}
               <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
               {% endif %}
</ul>