boardgame_platform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("boardgames.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

boardgames/urls.py
from django.urls import path
from boardgames.views import (
    index,
    BoardGameListView,
    EventListView,
    PlayerListView,
    BoardGameDetailView,
    EventDetailView,
    EventCreateView,
    toggle_assign_to_event,
    EventUpdateView,
    EventDeleteView,
    BoardGameCreateView,
    BoardGameUpdateView,
    BoardGameDeleteView,
    RegisteredEventsByUserListView,
)

app_name = "boardgames"
urlpatterns = [
    path("", index, name="index"),
    path("boardgames/", BoardGameListView.as_view(), name="board-game-list"),
    path("events/", EventListView.as_view(), name="event-list"),
    path("players/", PlayerListView.as_view(), name="player-list"),
    path(
        "boardgames/<int:pk>/", BoardGameDetailView.as_view(), name="board-game-detail"
    ),
    path("boardgames/create/", BoardGameCreateView.as_view(), name="board-game-create"),
    path(
        "boardgames/update/<int:pk>/",
        BoardGameUpdateView.as_view(),
        name="board-game-update",
    ),
    path(
        "boardgames/delete/<int:pk>/",
        BoardGameDeleteView.as_view(),
        name="board-game-delete",
    ),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event-detail"),
    path("events/create/", EventCreateView.as_view(), name="event-create"),
    path("events/update/<int:pk>", EventUpdateView.as_view(), name="event-update"),
    path("events/delete/<int:pk>/", EventDeleteView.as_view(), name="event-delete"),
    path("events/<int:pk>/toggle/", toggle_assign_to_event, name="event-toggle"),
    path("my_events/", RegisteredEventsByUserListView.as_view(), name="my-events"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("boardgames.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

boardgames/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser


class BoardGameGenre(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class BoardGame(models.Model):
    title = models.CharField(max_length=255, unique=True)
    genre = models.ForeignKey(BoardGameGenre, on_delete=models.SET_NULL, null=True)
    min_players = models.IntegerField()
    max_players = models.IntegerField()
    description = models.TextField()
    image_url = models.URLField()

    def __str__(self):
        return f"{self.title}"


class Player(AbstractUser):
    class Meta:
        ordering = ("username",)

    HOST_PLAYER_CHOICES = (
        ("Player", "Player"),
        ("Host", "Host"),
    )
    role = models.CharField(max_length=6, choices=HOST_PLAYER_CHOICES, default="Player")
    favorite_games = models.ManyToManyField(BoardGame, related_name="favorited_by")

    def __str__(self):
        return f"Player {self.username} with {self.role} role."


class Event(models.Model):
    class Meta:
        ordering = ["date"]
        unique_together = ("title", "date")

    title = models.CharField(max_length=255)
    host = models.ForeignKey(
        Player, on_delete=models.CASCADE, related_name="hosted_events"
    )
    game = models.ForeignKey(BoardGame, on_delete=models.CASCADE, related_name="events")
    date = models.DateTimeField()
    location = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.title} on {self.date.strftime('%Y-%m-%d %H:%M')}"


class Registration(models.Model):
    class Meta:
        unique_together = ("player", "event")

    REGISTER_CHOICES = (
        ("Registered", "Registered"),
        ("Canceled", "Canceled"),
    )
    player = models.ForeignKey(
        Player, on_delete=models.CASCADE, related_name="registrations"
    )
    event = models.ForeignKey(
        Event, on_delete=models.CASCADE, related_name="registrations"
    )
    status = models.CharField(
        max_length=10, choices=REGISTER_CHOICES, default="Registered"
    )
    registered_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Player {self.player.username} was {self.status} on {self.event}."

boardgames/forms.py
from django import forms


class BoardGameGenreSearchForm(forms.Form):
    genre = forms.CharField(max_length=255, required=False)


class EventGameSearchForm(forms.Form):
    game = forms.CharField(max_length=255, required=False)

boardgames/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic

from boardgames.forms import EventGameSearchForm, BoardGameGenreSearchForm
from boardgames.models import BoardGame, Player, Event, Registration


def index(request):
    num_games = BoardGame.objects.count()
    num_players = Player.objects.count()
    num_events = Event.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_games": num_games,
        "num_players": num_players,
        "num_events": num_events,
        "num_visits": num_visits + 1,
    }
    return render(request, "index.html", context=context)


class BoardGameListView(generic.ListView):
    model = BoardGame
    context_object_name = "boardgames"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(BoardGameListView, self).get_context_data(**kwargs)

        context["search_form"] = BoardGameGenreSearchForm()
        return context

    def get_queryset(self):
        queryset = BoardGame.objects.all()
        genre = self.request.GET.get("genre")
        if genre:
            queryset = queryset.filter(genre__name__icontains=genre)
        return queryset


class BoardGameDetailView(generic.DetailView):
    model = BoardGame
    context_object_name = "boardgame"


class BoardGameCreateView(LoginRequiredMixin, generic.CreateView):
    model = BoardGame
    fields = "__all__"
    success_url = reverse_lazy("boardgames:board-game-list")


class BoardGameDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = BoardGame
    fields = "__all__"
    success_url = reverse_lazy("boardgames:board-game-list")


class BoardGameUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = BoardGame
    fields = "__all__"
    success_url = reverse_lazy("boardgames:board-game-list")


class EventListView(LoginRequiredMixin, generic.ListView):
    model = Event
    context_object_name = "events"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(EventListView, self).get_context_data(**kwargs)

        context["search_form"] = EventGameSearchForm()
        return context

    def get_queryset(self):
        queryset = Event.objects.filter(date__gte=timezone.now()).order_by("date")
        game = self.request.GET.get("game")
        if game:
            queryset = queryset.filter(game__title__icontains=game)

        return queryset


class PlayerListView(LoginRequiredMixin, generic.ListView):
    model = Player
    context_object_name = "players"
    paginate_by = 5


class EventDetailView(LoginRequiredMixin, generic.DetailView):
    model = Event
    context_object_name = "event"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        event = self.get_object()

        registration = Registration.objects.filter(
            player=self.request.user, event=event
        ).first()

        context["registration"] = registration
        return context


class EventCreateView(LoginRequiredMixin, generic.CreateView):
    model = Event
    fields = "__all__"
    success_url = reverse_lazy("boardgames:event-list")


class EventDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Event
    fields = "__all__"
    success_url = reverse_lazy("boardgames:event-list")


class EventUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Event
    fields = "__all__"
    success_url = reverse_lazy("boardgames:event-list")


def toggle_assign_to_event(request, pk):
    event = get_object_or_404(Event, pk=pk)
    registration = Registration.objects.filter(player=request.user, event=event).first()

    if registration:
        if registration.status == "Registered":
            registration.status = "Canceled"
        else:
            registration.status = "Registered"
        registration.save()
    else:
        Registration.objects.create(
            player=request.user, event=event, status="Registered"
        )

    return redirect("boardgames:event-detail", pk=pk)


class RegisteredEventsByUserListView(LoginRequiredMixin, generic.ListView):
    model = Event
    template_name = "boardgames/events_list_registered_user.html"
    context_object_name = "events"
    paginate_by = 10

    def get_queryset(self):
        return (
            Event.objects.filter(
                registrations__player=self.request.user,
                registrations__status="Registered",
            )
            .order_by("date")
            .distinct()
        )

templates/boardgames/boardgame_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Boardgame?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/boardgames/boardgame_detail.html
{% extends "base.html" %}

{% block content %}

  <h2>{{ boardgame.title }}</h2>
  <p><strong>Genre:</strong> {{ boardgame.genre.name }}</p>
  <p><strong>Players:</strong> {{ boardgame.min_players }} - {{ boardgame.max_players }}</p>
  <p><strong>Description:</strong> {{ boardgame.description }}</p>
  <img src="{{ boardgame.image_url }}" alt="{{ boardgame.title }}" width="300">
  <h1>
    <a href="{% url 'boardgames:board-game-delete' pk=boardgame.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'boardgames:board-game-update' pk=boardgame.id %}" class="btn btn-primary">
      Update
    </a>
  </h1>
{% endblock %}

templates/boardgames/boardgame_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create an BoardGame</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/boardgames/boardgame_list.html
{% extends "base.html" %}


{% block content %}

  <h1>
      Board games List
      <a href="{% url 'boardgames:board-game-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>

  {% if boardgames %}
    <ul>
      {% for game in boardgames %}
        <li>
          <a href="{% url "boardgames:board-game-detail" pk=game.id %}">{{ game.id }}</a>
          {{ game.title }} ({{ game.genre }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no games in our base</p>
  {% endif %}
  {% block search %}

  <form method="get" class="form-inline mb-4">
  {{ search_form  }}
  <button type="submit" class="btn btn-primary">
    <i class="icon-search3"></i>
  </button>
</form>
  {% endblock %}
{% endblock %}

templates/boardgames/event_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete event?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/boardgames/event_detail.html
{% extends "base.html" %}

{% block content %}


  <h2>{{ event.title }}</h2>
  <form method="post" action="{% url 'boardgames:event-toggle' event.pk %}">
  {% csrf_token %}
  {% if registration.status == "Registered" %}
    <button class="btn btn-danger">Cancel participation in the event</button>
  {% else %}
    <button class="btn btn-success">Sign up for an event</button>
  {% endif %}
</form>

  <p><strong>The best host:</strong> {{ event.host }}</p>
  <p><strong>Game:</strong> {{ event.game }}</p>
  <p><strong>Date:</strong> {{ event.date|date:"F j, Y, H:i" }}</p>
  <p><strong>Location:</strong> {{ event.location }}</p>

  <h1>
    <a href="{% url 'boardgames:event-delete' pk=event.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>

    <a href="{% url 'boardgames:event-update' pk=event.id %}" class="btn btn-primary">
      Update
    </a>
  </h1>
{% endblock %}

templates/boardgames/event_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create an Event</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit">
  </form>
{% endblock %}

templates/boardgames/event_list.html
{% extends "base.html" %}


{% block content %}


  <h1>
      Event List
      <a href="{% url 'boardgames:event-create' %}" class="btn btn-primary link-to-page">
        Create
      </a>
    </h1>


  {% if events %}
    <ul>
      {% for event in events %}
        <li class="mb-2">
          <strong><a href="{% url "boardgames:event-detail" pk=event.id %}">{{ event.title }}</a></strong><br>
  <span>{{ event.date|date:"F j, Y, H:i" }} — {{ event.host }} — {{ event.location }}</span>
</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no games in our base</p>
  {% endif %}
   {% block search %}

  <form method="get" class="form-inline mb-4">
  {{ search_form  }}
  <button type="submit" class="btn btn-primary">
    <i class="icon-search3"></i>
  </button>
</form>
  {% endblock %}
{% endblock %}

templates/boardgames/events_list_registered_user.html
{% extends "base.html" %}
{% block content %}

<h2>My events</h2>

{% if events %}
  <ul>
    {% for event in events %}
      <li>
        <strong><a href="{% url "boardgames:event-detail" pk=event.id %}">{{ event.title }}</a></strong> — {{ event.date }}
        ({{ event.location }}) — Game: {{ event.game.title }}
      </li>
    {% endfor %}
  </ul>
{% else %}
  <p>You haven't registered from any events.</p>
{% endif %}

{% endblock %}

templates/boardgames/player_list.html
{% extends "base.html" %}


{% block content %}

  {% if players %}
    <ul>
      {% for player in players %}
        <li class="mb-2">
  <strong>{{ player.username }}</strong><br>
  <span>id - {{ player.id }} — {{ player.role}}</span>
</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no players in our base</p>
  {% endif %}
{% endblock %}